### ISSUE TITLE
Error when installing dependencies on Linux

### ISSUE THREAD

**Issue by dmytrobondarchuk** [dmytrobondarchuk/FreeDiscovery#1]
**Summary:** Error "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dctv1gwb/xgboost/" is present when installing dependencies with using requirements_pip_unix.txt file on Linux
**Environment:** Ubuntu Mate 16.04.1 LTS (Xenial Xerus) 64-bit, installed Miniconda 64 bit for Python 3.5 
**Steps to Reproduce:**
```
1. git clone https://github.com/FreeDiscovery/FreeDiscovery.git
2. cd FreeDiscovery
3. conda create -n freediscovery-env --file build_tools/requirements_conda.txt python=3.5
4. source activate freediscovery-env 
5. pip install -r build_tools/requirements_pip_unix.txt
```

**Result:** Error "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dctv1gwb/xgboost/" is present.

[requirements_pip_unix_install_log.txt](https://github.com/dmytrobondarchuk/FreeDiscovery/files/669388/requirements_pip_unix_install_log.txt)

**Comments:** If ignore this error and try to run the test suite error appears. This error also blocks to run an example and produces errors. Using requirements_pip_win.txt instead of requirements_pip_unix.txt fixes this problem. Perhaps the reason lies in xgboost.

**Comment by rth** [comment]
@dmytrobondarchuk Thanks for submitting this issue!
Could you please attach the full output log with the traceback? 
What happens if you just do steps 1-4 then run 

     pip install xgboost==0.4a30

Do you get the same error?

P.S: also could you please rename this issue to something simpler like "Error when installing dependencies on Linux" (otherwise the email subject github sends is not very readable) :)

**Comment by dmytrobondarchuk** [comment]
Yes, if I just do steps 1-4 and then run
` pip install xgboost==0.4a30`
I get the same error.
[install_xgboost_log.txt](https://github.com/dmytrobondarchuk/FreeDiscovery/files/669396/install_xgboost_log.txt)

But when I tried to understand more detail this problem, I found the solution.
The problem was caused by lack of correctly installed pip3. 
So this command
`sudo apt install python3-pip`
solved the problem. After that all steps to install FreeDiscovery executed without errors :)

P.S: Also, I would like to thank you for your valuable advice and guidance.

**Comment by rth** [comment]
That is interesting, I think the relevant error in the logs is,
```
make: g++: Command not found
```
so it's can't fine the C++ compiler to install xgboost. When you install `python3-pip` it must also install `g++` (not sure about that). Normally, minconda environement has it's own version of `pip` so installing system pip should not change anything, but it's an interesting problem.

I'm tempted to remove `xgboost` dependency altogether (as it's actually not used right now) and set `pip` as an explicit dependency in `requirements_conda_*`. Thanks for reporting this.

**Comment by rth** [comment]
Removed the xgboost dependency althogether in https://github.com/FreeDiscovery/FreeDiscovery/commit/146f3d315be0f6fccce972ca7f53aca1b38e1ad1 so it shouldn't be an issue anymore.
