### ISSUE TITLE
Incorrect link

### ISSUE THREAD

**Issue by dmytrobondarchuk** [dmytrobondarchuk/FreeDiscovery#2]
Incorrect link is present on this page:
https://github.com/FreeDiscovery/FreeDiscovery/tree/master/examples

![screenshot](https://cloud.githubusercontent.com/assets/16905495/21434911/70f287a8-c87f-11e6-9839-f95743e03f89.png)

**Comment by rth** [comment]
No actually, that one is fine, it's just a weird format for url links in .rst files, so it can render correctly in the documentation,  https://freediscovery.github.io/doc/dev/examples/index.html  Thanks for checking it!
