### ISSUE TITLE
Typo in text

### ISSUE THREAD

**Issue by dmytrobondarchuk** [dmytrobondarchuk/FreeDiscovery#3]
There is a typo on the page
https://freediscovery.github.io/doc/dev/installation_instructions.html

![screenshot](https://cloud.githubusercontent.com/assets/16905495/21435372/2c54a0ba-c882-11e6-85bb-05b4270528c1.png)

**Comment by rth** [comment]
Thanks!

**Comment by rth** [comment]
Fixed in https://github.com/FreeDiscovery/FreeDiscovery/commit/146f3d315be0f6fccce972ca7f53aca1b38e1ad1
