### ISSUE TITLE
Check for broken links in the docs

### ISSUE THREAD

**Issue by rth** [dmytrobondarchuk/FreeDiscovery#4]
What could be useful is to make a small script that crawls the documentation pages and checks that there are no broken links (e.g. links that return an HTTP 404 Error).

Such a link could be, for instance, named `docs_check_broken_links.py` to be put under the `doc/` folder, and would be executed as,
```bash
source activate freediscovery-env
python doc/check_links_in_docs.py BASE_URL
```
where BASE_URL could be for instance `https://freediscovery.github.io/doc/0.7/`, and print a list of URL with broken links (only for local links within the domain  BASE_URL) together with the URL of the page where it happened. It is OK if this requires to install some extra dependencies. Would this be difficult to do, do you think @dmytrobondarchuk  ?

**Comment by dmytrobondarchuk** [comment]
Ok, I`ll try to do this.

**Comment by dmytrobondarchuk** [comment]
I made this script.  It crawls the documentation pages and checks that there are no broken links (e.g. links that return an HTTP 404 Error). This script is named `check_links_in_docs.py` and is located in the doc/ folder. The crawler can be executed as,
```
source activate freediscovery-env
python doc/check_links_in_docs.py BASE_URL
```
where BASE_URL could be for instance https://freediscovery.github.io/doc/0.7/ . The script prints a list of URL with broken links together with the URL of the page where it happened. It also creates in the `doc/` folder the text file `list_of_URL_with_broken_links.txt`  with the list of URL with broken links together with the URL of the page where it happened.

**Comment by rth** [comment]
Great, thanks! Let's move this discussion to your PR. Closing this issue.
